# MODE DEVELOPPEMENT

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Désactive le cache de Thymeleaf pour voir les modifs en direct

spring.thymeleaf.cache=false

# Affiche plus de détails dans la console

# debug=true


# SERVEUR

server.port=${PORT:8080}


# BASE DE DONNEES POSTGRES

# spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fdl_db}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fdl_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA (Hibernate)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# logging.level.org.hibernate.type.descriptor.sql=OFF

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# THYMELEAF

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML


# JWT

jwt.secret=${JWT_SECRET:6XRTJnygl8/qufbd2p2bmJ71ZUK0fWJ0APlL8sO8FPc=}
jwt.expiration=86400000


# UPLOAD

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
app.upload.dir=${UPLOAD_DIR:uploads}



# CLOUDINARY

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}